/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RDB_H_RPCGEN
#define _RDB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define DATABASE "roster.dat"
#define MAX_STR 256

struct record {
	char *first_name;
	char *last_name;
	char *student_id;
	char *major;
	char *level;
	char *user_id;
};
typedef struct record record;

#define RDBPROG 0x20000001
#define RDBVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LASTNAME_KEY 1
extern  record * lastname_key_1(char **, CLIENT *);
extern  record * lastname_key_1_svc(char **, struct svc_req *);
#define STUDENTID_KEY 2
extern  record * studentid_key_1(char **, CLIENT *);
extern  record * studentid_key_1_svc(char **, struct svc_req *);
#define USERID_KEY 3
extern  record * userid_key_1(char **, CLIENT *);
extern  record * userid_key_1_svc(char **, struct svc_req *);
extern int rdbprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LASTNAME_KEY 1
extern  record * lastname_key_1();
extern  record * lastname_key_1_svc();
#define STUDENTID_KEY 2
extern  record * studentid_key_1();
extern  record * studentid_key_1_svc();
#define USERID_KEY 3
extern  record * userid_key_1();
extern  record * userid_key_1_svc();
extern int rdbprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_record (XDR *, record*);

#else /* K&R C */
extern bool_t xdr_record ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RDB_H_RPCGEN */
